UPDATE public.stories SET title = 'Get paid for your knowledge, no matter who you are. We all have a unique story, skills, and life experience that can be used in service to others. The key is consistent selfless service and sharing the best of what you know for free. To stand out and rise above the noise in the online marketing world, you have to serve at a level most are not willing to.  #monetizeyourknowledge #monetizeyourpassions #startacoachingbusiness #sellonlinecourses #beaunorton ' WHERE slug = 'tiktok-7244560847182335275';
UPDATE public.stories SET title = 'Do with it what you will #guitartok #guitarcover #rnbguitar #guitartutorial #chordprogression ' WHERE slug = 'tiktok-7226509036403871022';
UPDATE public.stories SET title = '#mentalhealth #shame #12steps #recovery #jung #truma #spirituality #addiction #selfhealing #healing ' WHERE slug = 'tiktok-7249811412535512362';
UPDATE public.stories SET title = 'Replying to @Kimberly   Blackrock loves people with Celiac Disease 😊 Hope you like corn! 🌽  #blackrock #vanguard #celiacdisease #cornprices #corn #sugarprices #commoditiestrading #brics #expertanalysis   ' WHERE slug = 'tiktok-7247582270171680043';
UPDATE public.stories SET title = 'Replying to @jpcguy89  final boss of home networking 😤 I personlly had not heard of these till you guys told me about them and OH MY GOD THEYRE SO COOL #techtok #wifi #internet #tech #smarthome #homekit #howto #networking #MoCA ' WHERE slug = 'tiktok-7248816309595655430';
UPDATE public.stories SET title = 'The WallenBurg Family 🚨  #wallenburgfamily #wallenburg #ericsson #blackrock #sweden ' WHERE slug = 'tiktok-7248119148713217322';
UPDATE public.stories SET title = '2023 vs the great depression #greenscreen #fyp #trending #capitalism #america #usa #inflation #millennial #genz #blowthisup #comparison ' WHERE slug = 'tiktok-7244264038501371182';
UPDATE public.stories SET title = 'YouTube shorts, Facebook reels, Tiktok.. all of these platforms are on fire and you should be taking advantage of the free reach that they provide. You want to maximize that even more? Get really educated on PAC - platforms and culture, aka the features and tools that are working on each platform as well as the relevant topics in macro culture. Hope this helps somebody! ' WHERE slug = 'tiktok-7245787271432080683';
UPDATE public.stories SET title = 'This period of time will be called the great divorce and it is the first step towards healing our capacity to have love. #dating #thegreatdivorce #romanticrelationship ' WHERE slug = 'tiktok-7234571457873906990';
UPDATE public.stories SET title = '#stitch with @Scott Galloway PART 1 OF 2 - what I think men are missing ' WHERE slug = 'tiktok-7230290513306635566';
UPDATE public.stories SET title = 'How to make money online #stocks #tiktokban #money #business ' WHERE slug = 'tiktok-7243890794095021354';
UPDATE public.stories SET title = 'What really is the Deep State? #RobertFKennedyJr gives us the real deal on #theallinpodcast ' WHERE slug = 'tiktok-7232437023116873006';
UPDATE public.stories SET title = 'Seamless Key Change Warmup ✨ Seams are for clothes 👔 not key changes. Check out Adam''s new Genius Chord Warmups course [link in bio] . . . #musictutorial #pianotutorial #jazztutorial #jazztok #pianotok #musictok #piano #jazz #music #jazzmusic #jazzpiano #chords #warmup #openstudiojazz #jazzeducation #comping #jazzpianosolo #jazzlesson #jazzmaster #jazzmusicians #instapiano #instajazz #jazzpodcast #keychange #chord #chordprogression ' WHERE slug = 'tiktok-7247923758856719662';
UPDATE public.stories SET title = '#CapCut how did this work? A 7 min episode meditation on @Oprah healed my #woundedinnerchild somehow. #gealingwounds #childhoodscars #motherwound #toxicmother #toxicfamily ' WHERE slug = 'tiktok-7243993544665386286';
UPDATE public.stories SET title = 'Are you challenged with cold intolerance?  Here are 5 deficiencies to consider and remedies to help! Do your fingers or toes go white or become numb when exposed to cold?  Or, do you feel cold all the time, even in mildly cold temperatures? Here are 5 deficiencies to pay attention to and remedies to consider: 1. Low iodine, selenium, or zinc  - Support thyroid function. Best sources: shellfish, brazil nuts, liver, lamb, eggs, cashews, walnuts, brown rice 2. Low iron  - Anemia symptoms.  This could come from low iron or low vitamin B12. Best sources of iron: red meat, pistachios, pine nuts, sesame seeds, pumpkin seeds, parsley, blackstrap molasses 3. Low vitamin B1  - Raynaud’s syndrome where your fingers may turn blue when you come in contact with the cold. Best sources: vitamin B1 supplements and inositol hexanicotinate 4. Low chromium  - Underlying insulin resistance potential issue. Chromium can help keep insulin sensitive.  Best sources: oysters, liver, egg yolks, grapes, black pepper, molasses  5. Low vitamin B1, B2, B3, B5, and B6  - If you’re deficient in B vitamins, you could have a hard time making cellular energy because the mitochondria can’t work. Best sources: vitamin B complex, nutritional yeast,  Additional remedy considerations: + evening primrose oil + quercetin + wormwood + magnesium Looking to learn more, tap into more resources, or get started on a precision wellness plan? Join our NEW Precision Wellness Secrets For Busy Parents Facebook group: https://www.facebook.com/groups/precisionwellness    Study: https://www.ncbi.nlm.nih.gov/books/NBK232854/ #cold #vitamins #food #nutrition #autoimmune #rootcause #parenting #mom #dad #parents #health #wellness #functionalhealth #functionalmedicine #naturopathy #naturopathic #integrativehealth #ricewellnesscenter' WHERE slug = 'tiktok-7247569554627398954';
UPDATE public.stories SET title = 'Highly recommend watching the whole talk really insightful #teachersoftiktok #autisticsocialskills #neurodivergent #neurodivergenttiktok #pdachild #pathalogicaldemandavoidance #autismawareness #adhdchild #adhdchildren #autisticcreator #autisticchild #autismcommunity #learnontiktok #enoughisenough #schoolsystem #ehcp #fyp #foryoupage #naughtychild #schooltrauma #pdaautism #pdaautismtiktok #senparentsupport #senparentsoftiktok #parentsoftiktok ' WHERE slug = 'tiktok-7237131806607199514';
UPDATE public.stories SET title = 'Replying to @figmamma High tunnel grant info #farmserviceagency #nrcs #naturalresourcesconservationservices #hightunnelgrant #grants #growingfood ' WHERE slug = 'tiktok-7226077686035270958';
UPDATE public.stories SET title = 'If you don''t know who I am, my name is Vinh Giang - I''m part magician, part keynote speaker and part communication teacher - yep I''m a bit of a mixed breed 😅  These 3 points I shared at @levelasian ''s recent event have helped me navigate my untraditional career path over the last decade and I hope they give you a bit of inspiration as well 👊' WHERE slug = 'tiktok-7246665427496062209';
UPDATE public.stories SET title = 'Working hard for 20 years to achieve a goal only to find out it doesn''t make you happy? It''s not uncommon. #success #happiness #internalfulfillment #RickRubin #RubinMotivation #InspiredByRickRubin #RubinWisdom #MotivationFromRickRubin #RubinTransformation #RickRubinQuotes #MotivatedByRickRubin #RubinVibes #MotivationMentorRickRubin' WHERE slug = 'tiktok-7246755358218276142';
UPDATE public.stories SET title = '#Gen x#best fuck around and find out moments#who let Gen x off the hook#if I leave anybody out please forgive me I am 50 th@Bryan 인희 Lee@Kelly Manno😎 @EricaSaysStuff @Bigdoglefty @bobbyzworld90@jensally @Mama Jenn @Jen @ms.dgaf @“The” Dadbod Veteran @Alainah ' WHERE slug = 'tiktok-7246047535658290474';
UPDATE public.stories SET title = 'Replying to @cg.pilot Low Views Update…What to do now to grow on tiktok. #tiktokgrowth #tiktokgrowthhacks #howtogrowontiktok #fyp #tiktokseo ' WHERE slug = 'tiktok-7214165817968069930';
UPDATE public.stories SET title = '👂🏽this is SO important for you to understand. #manifestationtips #lawofassumption #lawofassumptiontips #lawofattraction #youareacreator #lawofassumption101 #quantumjumping ' WHERE slug = 'tiktok-7246448239644396843';
UPDATE public.stories SET title = 'Grant Cardone shares his very controversial thoughts on how to get out of the middle class #grantcardone #middleclass #wealth #money #wealthymindset ' WHERE slug = 'tiktok-7244649300372770075';
UPDATE public.stories SET title = 'pls pls don''t eat mushrooms without professional advisory this is historical and vikings had ancestral knowledge about safe ways to use the aminita. it is a highly poisonous mushroom that CAN kill you if eaten so don''t play w it they were consuming microscopic amounts. #medicinal #strangepast #weirdhistory #history #facts #strangepast #weirdfacts ' WHERE slug = 'tiktok-7245048070365367598';
UPDATE public.stories SET title = 'A simple rhythmic trick for instant groove 🎵 #rhythmtips #musicproducer #vocaldelay #musictheorytiktok #musicproducerhacks #basicmusictheory ' WHERE slug = 'tiktok-7242727695807810843';
UPDATE public.stories SET title = 'Replying to @blackmindandbody1 theres that old saying about history not known, is doomed to be repeated. #americanhistory #blackhistory #classism #proletariat #oldsouth ' WHERE slug = 'tiktok-7239757647996603691';
UPDATE public.stories SET title = 'Best Email Subject Line for Sales 📲 #emailmarketing #salestips #entrepreneur #emailoutreach #salestraining' WHERE slug = 'tiktok-7244180281291263274';
UPDATE public.stories SET title = 'Hermes-13B - New AI LLM, Outperforms GPT4 🪦!? 🤯 #ai #chatgpt #gpt4 #gpt3 #hermes13b #gpt4all #aimodel #artificialintelligence #openai ' WHERE slug = 'tiktok-7242601150506224902';
UPDATE public.stories SET title = '#adhd #drrussellbarkley #russellbarkley #qualiafocus @Neurohacker ' WHERE slug = 'tiktok-7229802708096781614';
UPDATE public.stories SET title = 'Replying to @d33ryboy here it is —> Particles and Fields Sean Carroll x The Royal Institution #science #education #universe #space #physics #quantumphysics @maskedrandomness @maskedrandomness @maskedrandomness ' WHERE slug = 'tiktok-7215776853444021550';
UPDATE public.stories SET title = 'Steal my A.I. Automation to completely convert a news article to Instagram post (end to end) using @Zapier and @Tango #businessautomation #openai #chatgpt #socialmediamarketing #digitalmarketing #brandnat #nataliechoprasert ' WHERE slug = 'tiktok-7239943919478344978';
UPDATE public.stories SET title = 'Do you actually own anything?  Learn how the state holds rhe title on most things we think we own. #3things #business #businessowner #america #privacy #breakingnews #ownership ' WHERE slug = 'tiktok-7241692246507064618';
UPDATE public.stories SET title = 'Pentatonic Triad Warmup . . . #musictutorial #pianotutorial #jazztutorial #jazztok #pianotok #musictok #piano #jazz #music #jazzmusic #jazzpiano #chords #warmup #openstudiojazz #jazzeducation #comping #jazzpianosolo #jazzlesson #jazzmaster #jazzmusicians #instapiano #instajazz #jazzpodcast ' WHERE slug = 'tiktok-7238283201586728234';
UPDATE public.stories SET title = '#bankingsystem #contracts #agrements  #law  #loans #fyp #playthegame   how to get them back ' WHERE slug = 'tiktok-7243691547731037466';
UPDATE public.stories SET title = 'Settlement time #google #classaction #classactionlawsuit #classactionsettlement #money #privacy #lawsuit #lawyer ' WHERE slug = 'tiktok-7242485967360150826';
UPDATE public.stories SET title = 'Anton Kreil the Ex Goldman Sachs trader talks about assets vs liabilities and gives his thoughts on renting vs mortgage #asset #liability #mortgage #rent #finance ' WHERE slug = 'tiktok-7229151924329778458';
UPDATE public.stories SET title = 'Learning to PAUSE when I feel triggered has literally saved my life. Been a long road dealing with anger and I still have to constantly be mindful of it. #angry #angerissues #emotionalintelligence #mentalhealth #spiritualitytiktok #couplestherapy #realtionships ' WHERE slug = 'tiktok-7239461016881351979';
UPDATE public.stories SET title = 'You need these 5 legends in your business to hit $10M/year in revenue.   The closer.   The fixer.   The artist.   The hacker.   The visionary.   These 5 savages can do damage.  Assemble your Avengers. ' WHERE slug = 'tiktok-7209103281757457710';
UPDATE public.stories SET title = 'This is the power of saying YES AND. Most people say YES BUT in a conversation which doesn''t build on their response, it actually negates it. If you want to keep a conversation going in a positive direction, use YES AND more!' WHERE slug = 'tiktok-7239982492927773953';
UPDATE public.stories SET title = 'I’m reflecting on how bonkers having a LIVE SHOW was and catching up on work, so here is the intro video from my live show to give you a little love today ♥️ #keepitupcutie #mashedpotatobrain #exhaustedmillennial #everythingismadeup ' WHERE slug = 'tiktok-7239158684994063659';
UPDATE public.stories SET title = 'The “2-Minute Rule” from the “Triple-Two System” Which can help Build Consistency when trying to Incorporate New Habits in our Everyday Lives🏆: Full Video on the “Cajun Koi Academy” YouTube Channel (Link in Bio) #focushacks #productivity #acheiveyourgoals #studentsuccess #discipline #selfdevelopment #healthyhabits #cajunkoiacademy ' WHERE slug = 'tiktok-7233564590250986758';
UPDATE public.stories SET title = 'Truth bomb 🤯🥹 grab a guided shadow work journal to meet yourself at the deepest level. ➡️ #shadowwork #therapytok #shadowworkprompts #relationshipadvice #zenfulnote #whatisshadowwork #shadowworkjournal ' WHERE slug = 'tiktok-7226442106695339307';
UPDATE public.stories SET title = 'PT 2 Coming next! 👌 Before you consider calling a collection agency to pay the debt. Make sure you send in a deb validation request first. You always want to sending it to validation request before just paying a collection. #collection #credit #debt #creditcard #smallbusinesscheck #savingmoney #finance #mortgage #fyyyyyyyyyyyyyyyy #business ' WHERE slug = 'tiktok-7227259725845499182';
UPDATE public.stories SET title = 'What are your favorite capitalism survival strategies? These are some of mine. .#survivingcapitalism #internalizedcapitalism #latestagecapitalism #anticapitalism #anticapitalist ' WHERE slug = 'tiktok-7239850344090488107';
UPDATE public.stories SET title = '#CapCut Daily business, mindset and life tips to help you bulld wealth! #wealth #sillybandzcreator #finance #entrepreneur #rich #moneytips #investing #smallbusiness #inspiration ' WHERE slug = 'tiktok-7232114173201698090';
UPDATE public.stories SET title = '#officialjuma #fyp #foryou #viral #mood ' WHERE slug = 'tiktok-7230344874850094363';
UPDATE public.stories SET title = 'Replying to @glitterbombtarget #qanda presented by @Actionsports #edu #answer #lawyersoftiktok #25script #potbrothersatlaw #knowyourrights #PoliceEncounter #cops ' WHERE slug = 'tiktok-7233484193408273706';
UPDATE public.stories SET title = 'Happy life simple life, this is not financial advice 🫡😂 #hamedtrades #stockmarket #stocktrader ' WHERE slug = 'tiktok-7239837839918206254';
UPDATE public.stories SET title = 'A weird unnatural condition is forced on electricity causing it to be lethal and dangerous. Link in bio for proof #donttellmeitcantbedone #debate #engineering #physics' WHERE slug = 'tiktok-7239481171221024046';
UPDATE public.stories SET title = 'Sound is the source of all creation. Sound gives form, sound gives life. There is a mind blowing video on YouTube where a guy makes his car waves with some specific frequencies, and also a video where a Bridge waves massively because of the frequency it was on, it would match the frequency of the wind and it started to wave till it collapsed.  Source of the video (Title on YouTube): Michio Kaku Explains Multiverse, Aliens & Quantum IMMORTALITY | 145 Summary of the Podcast:  This podcast with the physicist Michio Kaku discuss three fascinating topics: the multiverse, aliens, and quantum immortality. Here''s a breakdown of what each topic generally entails: Multiverse: Michio Kaku explores the concept of the multiverse, which suggests the existence of multiple universes beyond our own. He delves into theories such as the inflationary multiverse and the many-worlds interpretation of quantum mechanics. The discussion likely covers the possibility of parallel universes, different laws of physics, and the potential implications of a multiverse for our understanding of reality. Aliens: In this part of the podcast, Michio Kaku delves into the topic of extraterrestrial life. He might discuss the likelihood of intelligent life existing elsewhere in the universe, the search for extraterrestrial intelligence (SETI), and the potential implications of discovering alien civilizations. This could involve discussing various theories on how life might evolve on other planets and the technological advancements necessary for interstellar communication or travel. Quantum Immortality: Michio Kaku explores the concept of quantum immortality, a thought experiment rooted in quantum mechanics. It proposes that conscious observers could experience a form of immortality through the multiverse. The discussion might involve topics such as the role of observation in quantum theory, the relationship between consciousness and reality, and the philosophical implications of quantum immortality. Overall, this podcast episode offers a fascinating exploration of these speculative and thought-provoking topics from the perspective of a renowned physicist like Michio Kaku. #epigenetictips ' WHERE slug = 'tiktok-7233899168970935598';
UPDATE public.stories SET title = 'Don’t have a clear vision?   Take 30 minutes to write down your goals.   Feeling uninspired?  Focus on your health.   Feeling confused?   Take a break.   Have no purpose in life?   Take time to reflect.   Level up through reading, writing and mentors.   You control your future.   Start with systems and then scale.' WHERE slug = 'tiktok-7221347781951212843';
UPDATE public.stories SET title = 'You will also hear this in many Underlicks. “I miss you” from blink 182 played by @to@tomdelonge  and  @mark.hoppus1  and some of the memorable top lines from @remiwolf   Its glorious ❤️🎶🤖 . . #nirvana #justinbieber #kidlaroi  #songwritingtips #musicproduction #musictheory101 #underlick #songwritinginspiration #songwritingprocess #singersofTikTok #songwriterlife #musiccomposition #songwritingskills #songwritingjourney #songwritercommunity #musicproductiontips #songwriterstruggles #musicproducers #songwritingtipsandtricks #musicpublishingindustry #songwritingtipsforbeginners #ViB3machine #Musiciansoftiktok #songwritersoftiktok  #producersoftiktok #songmath ' WHERE slug = 'tiktok-7226860622321831214';
UPDATE public.stories SET title = '#shopify #dropshipping #shopifybusiness #shopifystoresetup #sidehustle2023 #entrepreneurslife #sidehustle ' WHERE slug = 'tiktok-7238113020583431450';
UPDATE public.stories SET title = '"Hey guys, are you ready to transform your life with the power of positive affirmations? Check out this amazing book that changed my life - it''s filled with techniques and exercises that will help you manifest your dreams and create a life you truly love. Start each day with positive intentions and watch as the universe responds. With daily affirmations, anything is possible. Trust the process and let''s manifest our best lives together! #affirmationmanifestation #lawofattraction #bookrecommendat' WHERE slug = 'tiktok-7236250645324483883';
UPDATE public.stories SET title = '*saves for later*' WHERE slug = 'tiktok-7235013403855555882';
UPDATE public.stories SET title = 'Replying to @racheljoy.onearth If you are interested in credit repair, starting and getting a LLC/EIN for a business, and/ or getting Business funding/ Business credit/ Business Line of Credit, to buy businesses and real estate. We also offer coaching and  a mentorship program. Just text whatever you''re interested in to (281) 853-8004 or go the therichgetrichard.com and I will take care of you. Thanks' WHERE slug = 'tiktok-7237934845194751274';
UPDATE public.stories SET title = 'the harsh truth of reality #lukebelmar  #lifeadvice  #truth ' WHERE slug = 'tiktok-7237311433900297473';
UPDATE public.stories SET title = 'A hill I’m willing to die on is that AI is a gift to us NeuroDs #adhdtools ##adhdtools #adhdproductivity #adhdmanagement #adhdapps #adhdtips #adhdmanaging #adhdtech #adhdtechsupport #aitools #aiapps #aitrend #aitechnology #aiautomation ' WHERE slug = 'tiktok-7235727158705147182';
UPDATE public.stories SET title = 'Chatgpt easily builds automations for you and if you don''t know how watch this cool combo I created in chatgpt plugins! all you need is @Zapier and "Show me" mind maps. sign up to my newsletter Stan. store/brandnat if you want to see a detailed tutorial on this! #openai #brandnat #nataliechoprasert #chatgpt #chatgptplugins #zapier #zapierpartner #ai #aitools #businessautomation #artificialintelligence ' WHERE slug = 'tiktok-7236161067154443527';
UPDATE public.stories SET title = 'Did I make it? 😲 #sidehustleideasforanyone #makemoneyonline #aiart#midjourneyart #passiveincomeideas #sidehustlesecrets ' WHERE slug = 'tiktok-7232211116393368859';
UPDATE public.stories SET title = 'Insane ai hack! 😱 #ai #artificialintelligence #ainews #aiart #gpt4 #chatgpt4 #chatgpt #chatgpt3 #openai #chatgpttutorial #elonmusk #elon #chatgptexplained #tech #technology #technews #web3 #chatgpt3 #chatgptbot #chatgptai #chatgpttutorial  #technologynews #business #businessowner #businessman #businesstips #businesscoach #businessquotes #businessideas Artificial intelligence viral tiktok Artificial intelligence in business Artificial intelligence websites Artificial intelligence learning Artificial intelligence robots Artificial intelligence trend app' WHERE slug = 'tiktok-7216372179317837063';
UPDATE public.stories SET title = '99% of you don’t know this about ChatGPT 🤯 #ai #robotics #technology #chadgpt #chatgptwriterai #googlechrome #emailwriting #chatgpt #chatgpt3 #chatgpthack #chatgptai #chatgptforcreators #chatgpttutorial #chatgptprompts ' WHERE slug = 'tiktok-7205209092879682822';
UPDATE public.stories SET title = 'Learn how to prompt ChatGPT correctly for mind-blowing results! Let’s transform a generic ad into a powerful, inspiring one with a simple framework! #TikTokTips #ChatGPT #AI #AIHacks #ContentCreation #Algorithm #cidi  #CareerBoost #Alacademy' WHERE slug = 'tiktok-7228277474679983387';
UPDATE public.stories SET title = 'let''s go part 2! these prompts are the literal chefs kiss. number 4 is my favorite! #ai #openai #chatgpt #chatgpt4 #chatgptprompts #chatgptprompt #letsgo #artificialintelligence #wfhhacks #wfh #10hr10kworkmonth #antiworkaholic #antiworktiktok #moneymoves #nojob #no9to5 #success #work #business #sidehustle #freelancer #freelance #becomeagenuis #genius ' WHERE slug = 'tiktok-7219098172113571115';
UPDATE public.stories SET title = 'Top 2 and it aint 2' WHERE slug = 'tiktok-7212348917571194154';
UPDATE public.stories SET title = 'This is the best advice for TikTok growth you’ll ever hear. #tiktoktips #contentcreatortips #creatortips #tiktokgrowth #tiktokstrategy #tiktoktipsandtricks ' WHERE slug = 'tiktok-7208287838171827461';
UPDATE public.stories SET title = 'Replying to @gracie✨ /  travel tiktok tips for #contentcreators #socialmediatips #influencertips ' WHERE slug = 'tiktok-7213729922349665542';
UPDATE public.stories SET title = '🚨How to edit VIRAL videos 100% with AI #ai #videoedit #videos #midjourney #techtok #tech #aitools #artificialintelligence ' WHERE slug = 'tiktok-7220581620737297710';
UPDATE public.stories SET title = 'ChatGPT Web Browsing For Email Marketing Campaigns Is Next Level! #chatgpt #business #gpt4 #onlinebusiness #emailmarketing #wifimoney #ai #agency #onlinebusiness #makemoneywithai #zapier #gohighlevel' WHERE slug = 'tiktok-7233255219889507627';
UPDATE public.stories SET title = '#digitalmarketing #marketingai #landingpage #copywriting #logo #graphic #blockpost ' WHERE slug = 'tiktok-7231539783347064069';
UPDATE public.stories SET title = 'Here’s my MILLION DOLLAR email template 💰👍💰 See Below #sales #salestraining #salestips #email  Pamela, Thank you for a great call today. The purpose of this email is to summarize my understanding of our conversation in terms of the current situation, training needed, and offer the next step in helping XXXXX increase your topline revenue by $432,000 per month taking annual sales from $5,184,009 to $10,368,000 without increasing your marketing budgets.   Current Situation: Sales and topline revenue have remained flat for 2021 and 2022 at $5,184,000. The board is asking you to double your revenue by Q1 2024 and you would like to do this without increasing your current ad spend.   Training Needed: Good is not “good enough” at XXXX You want people fired-up and outperforming competing design firms in every phase of the game.  From greeting the prospect, determining wants and needs, selecting a solution, building value, making a proposal and closing the sale. You are looking for the edge that will double your annual sales without increasing your current $22,000 per month in total ad spend. Based on everything you told me, I believe the Easton University System is just what you are looking for.    Next Steps: Based on our conversation, Easton University portal access along with weekly LIVE coaching with me will give your people the edge you are looking for. You can enroll your entire 93 person team for $2999 per month.   I have limited availability for the private LIVE Training we discussed and have attached a quote to get you on my calendar.    As promised, I will call you Thursday if I haven’t heard from you before then.   Does this match what you had in mind? Did I miss anything?' WHERE slug = 'tiktok-7223464572978646318';
UPDATE public.stories SET title = 'here is a podcast and youtube editing hack that will save you hours!! @getmunch takes your long form video content and quickly converts it to engaging 9:16 short form video clips that you can repurpose on TikTok, IG reels, Youtube shorts or Facebook reels #microinfluencertiktok #podcastediting #youtubeediting #podcastersoftiktok #podcasttips #podcastersontiktok #youtubeshorts #getmunch   ' WHERE slug = 'tiktok-7223430609681534251';
UPDATE public.stories SET title = 'What happens when you enter a url in your browser - Software engineer interview queestions - 25 #softwareengineering #programming #techjobs #softwaredeveloper #interviewtipsandtricks #interviewtips #interviewquestions ' WHERE slug = 'tiktok-7218203536218131755';
UPDATE public.stories SET title = 'The best tips to grow on TikTok in 2023 as a musician! #socialmediamarketing #independentartist  #tiktoktips #socialmediatips  #marketingtips #musicmarketing #musicmarketingstrategies #contentstrategy #tiktokstrategy #greenscreen ' WHERE slug = 'tiktok-7226528121225284906';
UPDATE public.stories SET title = 'One of the best techniques there is for writing SEO content with ChatGPT. #chatgpthack #chatgptprompts #entrepreneur #digitalmarketing #smallbusiness #chatgpt #marketing ' WHERE slug = 'tiktok-7231884667237027099';
UPDATE public.stories SET title = 'If you want to build a one-person online empire, use these tools: - Figma - Beehiiv - Canva - Hypefury - Slack - Testimonial.to - Webflow - Kajabi - Shopify - Stripe - Notion Everything you need to create an online empire is at your fingertips. You got this. #business #brand #founder #fyp' WHERE slug = 'tiktok-7231216066918108459';
UPDATE public.stories SET title = 'How i plan to make 100k this summer with AI 💀#fyp #viral #ai #youtubeautomation   ' WHERE slug = 'tiktok-7235620262085938438';
UPDATE public.stories SET title = '🤯 MIT''s research on ChatGPT shows insane productivity boost! ⚡ 37% faster, 20% better, and happier while working! Equalizing skills & shrinking inequality. Only 20% are using it despite the benefits. Are you in? 🚀 #MIT  #ChatGPT  #productivityhack  #AI #worksmarternotharder  #techrevolution#FutureOfWork  #TikTokTech' WHERE slug = 'tiktok-7228607216247491846';
UPDATE public.stories SET title = 'Let me know what you guys think about this series idea! I''ll see if I can run with it! And if you have reccomendations for songs, let me know! #creedanceclearwaterrevival #ccr #badmoonrising #apocalypse #dark #eerie #reimagined #cover #piano #pianoballad #ballad #music #classicrock #blues #alternative #vibecheck ' WHERE slug = 'tiktok-7234570807454862634';
UPDATE public.stories SET title = 'Fred Again shares a deep and thoughtful quote about life from Stephen Colbert. It takes 2 minutes #fredagain #gratitude #life #music #fyp ' WHERE slug = 'tiktok-7234535918160350506';
UPDATE public.stories SET title = 'Carl Jung''s Most Important Speech: Narrated By Alan Watts (LIFE CHANGING) Song - Rok Nardin: Blood Moon Video - Happiness: Steve Cutts #alanwatts #carljung #psychology  #hopecore #philosophy ' WHERE slug = 'tiktok-7235256326748785926';
UPDATE public.stories SET title = '🚨The AI Tool That ACTUALLY POSTS Content For You, Not Just Creates It📈 #ai #artificialintelligence #aitools #ainews #chatgpt #technology #tech  #socialmedia #socialmediamarketing #contentcreator ' WHERE slug = 'tiktok-7235010866532355374';
UPDATE public.stories SET title = 'Best Content Creation Strategy for Hashtags. How to go viral. #contentcreator #contentcreators #ugccreator #socialmediamanager  #contentmarketing #contentstrategy #hastagstrending #hashtagideas  #besthashtagstrategy #contentideas ' WHERE slug = 'tiktok-7192334680203562286';
UPDATE public.stories SET title = 'Best Content Creation Strategy for Growth And Monetization. How to go viral. best seo Strategy for tiktok. Best hashtag Strategy. How to grow on tiktok. #howtogrowontiktok #howtogoviral #contentstrategy #besthashtagstrategy #howtogrowontiktok #contentideas #sidehustles #tiktokseohacks ' WHERE slug = 'tiktok-7232344438796848430';
UPDATE public.stories SET title = 'Best Content Creation Strategy for growth and monetization.. #socialmediamarketing #socialmediamarketingtips #tiktokgrowthtips #businesstips #contentstrategy ' WHERE slug = 'tiktok-7179355748529540398';
UPDATE public.stories SET title = 'GPT4ALL - Install a Chatbot Locally... FREE + No Internet or GPU Required to run! 🤯 #gpt4all #gpt4 #vincuna #chatbot #ai #aitools #chatgpt #openai #bard ' WHERE slug = 'tiktok-7235123391122918662';
UPDATE public.stories SET title = 'Install Auto-GPT in 1 minute Guide 1. Install Python - https://www.python.org/downloads/ 2. Make sure to select "Add Python to PATH" during install 3. Go to command "CMD" and check if its installed with the following commands python --version pip --version 4. Create an OpenAI API key. It uses a ton of tokens, so add billing https://platform.openai.com/account/api-keys 5. Now Download Auto-GPT from github and extract it 6. Edit the “.env.template” file with notepad and add the key you created on OpenAI 7. Open pinecone.io (Currently Waitlisted 1-2 Days) - Create free account and make an API key and add it to  paste it next to PINECONE_API_KEY and the enviroment next to PINECONE_ENV 8. Save file. Rename to text file .env 9. In command go to the chatgpt directory and type this command  "pip install -r requirements.txt" 10. To run AutoGPT type in this command "python -m autogpt" #ai #autogpt #auto-gpt #installautogpt #openai #pinecone ' WHERE slug = 'tiktok-7225096679626771739';
UPDATE public.stories SET title = 'I did NOT get a “thank you” after this one 😂 #1stamendment #freepress #citycouncilmeeting #tempe #freespeech #cussing #publiccomments #cityhall #swearwords #foryou #fyp #constitution #tyranny ' WHERE slug = 'tiktok-7234718806101347626';
UPDATE public.stories SET title = 'How To Make Faceless Videos Using AI #howtomakevideos #howtouseai #worksmarternotharder  #entrepreneur #contentcreator #onlinebusiness  #ai #aitips #artificialintelligence #fyp ' WHERE slug = 'tiktok-7234847081595424046';
UPDATE public.stories SET title = 'chatgpt is just the tip of the #ai iceberg. these softwares are going to seriously transform our lives and make money for those who leverage it! #greenscreen #chatgpt #chatgpt4 #chatgpthack #chatgptprompts #chatgptai #openai #artificalintelligence #gammaai #perplexityai #perplexity #chatgpt3 #antiworktiktok #digitalmarketing #moneymoves #goldrush #makemoneyonline #moneytiktok💸💸 #sidehustle #aiera #airevolution ' WHERE slug = 'tiktok-7223424169789148458';
UPDATE public.stories SET title = 'Ninja-Level Technique for Writing SEO Content With ChatGPT. #chatgpt #chatgptprompts #chatgpt4 #sidehustles #businessideas #brandstrategytips #monetizeai #artificialintelligence ' WHERE slug = 'tiktok-7234718324029132078';
UPDATE public.stories SET title = '6 free and simple AI tools I wish I knew about earlier #ai #artificialintelligence #openai #aitools #aitoolsforbusiness #chatgpt #gpt4 #adobe ' WHERE slug = 'tiktok-7234692358049156394';
UPDATE public.stories SET title = 'A needlessly long back and forth on #utilitarianism #philosophy ' WHERE slug = 'tiktok-7234606882755743002';
UPDATE public.stories SET title = '#usefulclearnetsites #scaryai ##dopegptplugins web browsing makes chat gpt wayyy too powerful' WHERE slug = 'tiktok-7234378195712085275';
UPDATE public.stories SET title = 'Softwares, automation tools, systems are very businesses lifesaver. Utilize them to not only free your time but yourself from the business. ' WHERE slug = 'tiktok-7223112344610671914';
UPDATE public.stories SET title = 'You found THE video #ai #artificialintelligence #chatgpt ' WHERE slug = 'tiktok-7231999003678772507';
UPDATE public.stories SET title = '📣This is it#sidehustleideasforanyone #makemoneyonline #earnmoneyfromhome #passiveincomelifestyles #sidehustlesecrets ' WHERE slug = 'tiktok-7231386266380569882';
UPDATE public.stories SET title = 'WavTool: Unleash Your Music-Making Potential with AI-Accelerated Production Introduction: Music production has taken a significant leap forward with the introduction of AI-accelerated tools like WavTool. This innovative platform empowers musicians of all levels to create high-quality music using an AI assistant, all within the convenience of their web browser. In this blog post, we''ll explore the features and benefits of WavTool, and how it can enhance your music-making journey. Unleash Your Creativity: WavTool offers a comprehensive set of features designed to meet the needs of beginners, musicians, and producers alike. With side-chain compression, advanced synthesis capabilities, flexible signal routing, and more, WavTool provides the tools you need to bring your musical ideas to life. Whether you''re arranging a song, experimenting with different sounds, or refining your compositions, WavTool gives you the power to create music that meets your standards. Introducing Conductor AI: One of the standout features of WavTool is Conductor AI, an intelligent assistant that guides you through the music-making process. Even if you''re a complete beginner, Conductor can provide recommendations, explain concepts, and make changes to help you achieve the best sound possible. With Conductor by your side, you can overcome creative blocks, learn new techniques, and streamline your music-making experience. Seamless Browser-Based Experience: Gone are the days of complicated installations and tedious updates. WavTool offers a seamless music production experience directly within your web browser. Record, compose, produce, mix, master, and export your music all within the WavTool interface. This eliminates the barriers to entry and allows you to focus on what matters most: making music. For Everyone: WavTool is designed to cater to musicians of all levels. Whether you''re a beginner exploring music production for the first time, an experienced musician looking for new tools, or a producer seeking a versatile and user-friendly platform,  #WavTool #MusicProduction #AIAssistant #MusicMaking #CreativeProcess #BrowserBased #UnleashYourCreativity #MusicCreators #AIAcceleratedProduction #aimusic ' WHERE slug = 'tiktok-7233132202966469914';
UPDATE public.stories SET title = '9 addictions you must break to become your best self 🙏💯 #selfimprovement #growthmindset #mindsetmotivation #motivationalquote #masculineenergy #masculinity ' WHERE slug = 'tiktok-7232667753063222555';
UPDATE public.stories SET title = '#expatlife #expat #caribbeantiktok ' WHERE slug = 'tiktok-7232825758995975470';
UPDATE public.stories SET title = 'AI text-to-video generation is here! #ai #contentcreation #filmmaker #videoproduction #filmtok ' WHERE slug = 'tiktok-7206701356671896874';
UPDATE public.stories SET title = 'These new ai tools are a cheatcode to life! 🤫 #ai #undetectableai  #artificialintelligence #ainews #aiart #gpt4 #chatgpt4 #chatgpt #chatgpt3 #openai #chatgpttutorial #elonmusk #elon #chatgptexplained #tech #technology #technews #web3 #chatgpt3 #chatgptbot #chatgptai #chatgpttutorial  #technologynews Artificial intelligence viral tiktok Artificial intelligence in business Artificial intelligence websites Artificial intelligence learning Artificial intelligence robots Artificial intelligence trend app' WHERE slug = 'tiktok-7217639079612009736';
UPDATE public.stories SET title = 'Replying to @queenism.360 4-11-2023 sovereign in court part 3 #sovereignty #jurisdiction #conspiracy #court #alllaw #contracts #honorable #conditionalacceptance #ladyjustice #w9form #attorney #tona ' WHERE slug = 'tiktok-7220772414592929066';
UPDATE public.stories SET title = '#battlehymneoftherepublic #abolishtheatf #abolishtheirs #peoplekillpeople #assaultrifleban #2a ' WHERE slug = 'tiktok-7229750561866927403';
UPDATE public.stories SET title = '#faithdeconstruction #faithcrisis #atheism #existentialangst #postmodernism #nihilism #existentialcrisis #unaliveawareness  #mormonism #god #christianity #freewill #religion ' WHERE slug = 'tiktok-7231604771294088490';
UPDATE public.stories SET title = 'This week on What Could Go Right? we sat down with @Baratunde Thurston to talk about whether AI is pulling us apart or bringing us together. #progress #ai #newpodcastepisode #tech #baratundethurston #whatcouldgoright🤔 ' WHERE slug = 'tiktok-7229073873340321050';
UPDATE public.stories SET title = 'The American Dream?  #entrepreneur #future #business #housing #banking #success #money #truth More at www.gallagheruniversity.com' WHERE slug = 'tiktok-7210547867717602566';
UPDATE public.stories SET title = 'Synthetic Protiens work in human blood! #biologicalsciences #biomechanics #technology #medicine #medicineexplained #science #protein #biohacking #transhumanism' WHERE slug = 'tiktok-7215295486411099438';
UPDATE public.stories SET title = 'I ESCAPED THE MATRIX ⬇️ Every Single Job I worked, I realized I was simply trading in my hours for money which made me broke at any salary. 💵 YOU NEED TO STOP WASTING YOUR TALENT 💫 and PRECIOUS TIME 🕰️. JOIN THE A.I REVOLUTION 🤖 3 WAYS TO START ⬇️ 🤖 Automation Agency specializing in software (Go High Level link in our bio) or Zapier Mastery 🖼️ Midjourney (Join their 11M+ Discord Server) 💻 Create A.I Tools and Plugins (start with GitFluence and Codieum) If you want to surround yourself with a Community of Elite A.I Entrepreneurs and Influencers, JOIN THE CLUBHOUSE (Link In Our Bio) #ai #chatgpt #openai #tech #business #entrepreneurship #entrepreneur #education #hormozi #midjourney #recession #nocode #saas #airevolution #theaiclubhouse' WHERE slug = 'tiktok-7228366713912397061';
UPDATE public.stories SET title = 'Leave it to Khan Academy to make the coolest AI tool yet. This idea is going to make learning so much more enjoyable and im excited about its impact on the younger generation ' WHERE slug = 'tiktok-7229027725967772971';
UPDATE public.stories SET title = 'Replying to @BatMon882 David Icke take on the World… #pov #neverforget #davidicke #matrix #illuminati ' WHERE slug = 'tiktok-7215273580865621254';
UPDATE public.stories SET title = 'Replying to @Mario Martinez I didn’t learn this until 2 years into business. Get this book! #profitfirst #heatpressnation #heatpressmachine #tshirtbusiness #smallbusiness #howto #startingabusiness #heatpresstransfers #athomebusiness #books #fypシ ' WHERE slug = 'tiktok-7231222683529268523';
UPDATE public.stories SET title = 'My Top 35 AI Tools. #ai #artificialintelligence #openai #tech #technology I have spent 5 months using the best tools and sharing them on this channel. Make sure to follow to stay up to date as this grows.' WHERE slug = 'tiktok-7230901616126217515';
UPDATE public.stories SET title = '#educational #interesting #concent ' WHERE slug = 'tiktok-7230502420978076970';
UPDATE public.stories SET title = 'A new programming language 35000x as fast as python for AI development?! #mojo #modular #tensorflow #pytorch #ai #programming #python ' WHERE slug = 'tiktok-7230946633347878186';
UPDATE public.stories SET title = 'The simpsons on the American Middle Class 1 #simpsons #clip #middleclass #marxism #capitalism #historytok #robertreich #edutok #leftist ' WHERE slug = 'tiktok-7230126662258576667';
UPDATE public.stories SET title = 'IYKYK  #AIsummer #fypシ  #skills ' WHERE slug = 'tiktok-7226493648966290731';
UPDATE public.stories SET title = 'Also changed changed my work schedule to 11pm-6am. Which has been a super interesting experiment in working while others sleep. #llm #aiapi #customai' WHERE slug = 'tiktok-7229267943295683886';
UPDATE public.stories SET title = '💥Simulation Evidence Discovered! DMT reveals code behind a laser 🚀 Full video on YouTube - Dan Go Thoughts | The Discovery That Will Change Everything - DMT Reveals Code Behind a Laser  • 📺 Prepare for a reality check 🤯  • A year sgo I shared my discovery on my channel Dan Go Thoughts on YouTube, that you can see a coherent signal behind a diffracted 650nm laser while on DMT. I’m about to release an update video on the subjecf, so I figured I’d share a short version of the video on here. It indicates that an entire sliver of reality we aren’t aware of, is as real as our world.  • #DMT #SimulationTheory #LaserCode #laser#dangothoughts #science #discovery ' WHERE slug = 'tiktok-7226874827829988654';
UPDATE public.stories SET title = 'Here is a flywheel generator I built using Vortex Based Mathematics and the formula F=# of magnets x rpm/phase angle. as of now the volts and current climb at what appear to be an overunity rate of efficiency.  Will this generator self loop because of the increase and positioning of the phase coils? #tesla  #teslatok #science  #scienceexperiments  #share ' WHERE slug = 'tiktok-7215274387736579370';
UPDATE public.stories SET title = 'Its right infront of your eyes #symbols #anonymousofficial #thorsleftbaw #ancient ' WHERE slug = 'tiktok-7213893910869888262';
UPDATE public.stories SET title = 'Perpetual GPT - The next iteration of AutoGPT #autogpt #perpetualgpt #openai #chatgpt #ai #technology' WHERE slug = 'tiktok-7224245831858244907';
UPDATE public.stories SET title = '#unite #numbers #america ' WHERE slug = 'tiktok-7226009611076390190';
UPDATE public.stories SET title = 'The history of Earth Day, and the environmental movement in the U.S., from the 60s to the present. I made this back in 2019, so it’s missing some of the recent developments since then, but it still provides some context for where we’re at. Now that we’re here, what do we do? What are we doing right, and what to we need to do way more and way less of? #earthday #ecology #environmentalism #history ' WHERE slug = 'tiktok-7224917935024803115';
UPDATE public.stories SET title = '9 Mindblowing Tools for Filmmakers #ai #filmmaking #filmmakingtips #filmmakers #film #filmtok ' WHERE slug = 'tiktok-7218952383185833259';
UPDATE public.stories SET title = 'Replying to @Followmefornoreason I would never sell something that educates. #EducationalContent is always #free. Feel free to try it out! I’ll be constantly improving it, so #FollowForUpdates #TradingView #PineScript #Strategy #Crypto #NotFinancialAdvice #EducationalPurposes #MancinoWeb3' WHERE slug = 'tiktok-7199713411691810053';
UPDATE public.stories SET title = '#artificialintelligence #chamathpalihapitiya #fyp' WHERE slug = 'tiktok-7225270613357759790';
UPDATE public.stories SET title = 'This Figma plugin 🤤  #webdesign #webdesigner #webdesignertips #uxdesign #uidesign ' WHERE slug = 'tiktok-7226189219805482283';
UPDATE public.stories SET title = 'Is resetting the human age possible?  Aging in Reverse: Dr. David Sinclair talks about a possibility of reversing age and resetting the body age based on recent clinical studies. @Healthcare, Longevity & Beauty #lifespan #nmn #reveseaging  #nmnsupplement #edmylett  #longevity #nmnantiage  #helathylifestyle #drdavidsinclair #nadsupplement ' WHERE slug = 'tiktok-7225960093789998338';
UPDATE public.stories SET title = '3 AI tools we actually use 🤯 #foryou #fyp #ai #artificialintelligence ' WHERE slug = 'tiktok-7224892347933347115';
UPDATE public.stories SET title = 'contrary to headlines claiming that we''re rapidly transitioning away from fossil fuels it''s just not happening. #breakingnews #politicalmemes #political #politics #newsnation #news #funnyviralmemes #democrats #tikok #government #conservative #democrat #socialmedia #freedom #uk #usa #france #germany #russia #saudi #ukraine #europ #electricity #electrical #electrician #energy #power #electric #electricians #electricalengineering #electricianlife #engineering #electricalwork #renewableenergy #solar #electronics #solarenergy #cleanenergy #technology #construction #solarpower #electricalhacks #solarpanels #electricianproblems #electricalengineer #greenenergy #electricalcontractor #lighting #electricidad #electriciansofinstagram #sparky #tools ' WHERE slug = 'tiktok-7224378300263697691';
UPDATE public.stories SET title = 'Train chatGPT on any pdf document using langchain and pinecone #chatgpt #engineeringstudent #finalsweek #gpt4 ' WHERE slug = 'tiktok-7224220988047772955';
UPDATE public.stories SET title = 'Is this you? 🙋‍♀️🙋🙋‍♂️ The world’s greatest leaders, changemakers, creators and thought leaders honored their inner knowing that they are meant for something BIG, and so should you. 🎨 #multipassionate #multipassionate #multipassionatecreative #creative #changemaker #coach_anniepetsche #peptalk ' WHERE slug = 'tiktok-7222818123907648810';
UPDATE public.stories SET title = 'The debate gets heated on race, legacy admissions and past injustices #harvard #justice #philosophy #fypシ #affirmativeaction ' WHERE slug = 'tiktok-7221285322838134021';
UPDATE public.stories SET title = '#mccurtaincounty #mccurtaincountyoklahoma  #mccurtaingazette #mccurtaincountycommissioners #localelectionsmatter ' WHERE slug = 'tiktok-7223105009486040366';
UPDATE public.stories SET title = '#usefulclearnetsites Auto GPT are going to take off so fast its going to be crazy' WHERE slug = 'tiktok-7222104269829279002';
UPDATE public.stories SET title = 'responses that diffuse defensiveness. ' WHERE slug = 'tiktok-7215390252251237674';
UPDATE public.stories SET title = 'I added @GitHub #Codespaces support to #AgentGPT so you can run your autonomous #AI agent in your browser without installing anything.  cc @AI Learning Lab @Visual Studio Code @Rachel | AI Startup Founder 🤖 @Allie K. Miller ' WHERE slug = 'tiktok-7221978500268297478';
UPDATE public.stories SET title = 'Marianne Williamson announced she will be running for President #marianne2024 #mariannewilliamson #economicmindset #legalizedbribery #LetHerIn #corruptpolicies ' WHERE slug = 'tiktok-7206846410032024878';
UPDATE public.stories SET title = '3 ways the #world order is changing. #principles #raydalio #economics #geopolitics #debt' WHERE slug = 'tiktok-7221626631272729902';
UPDATE public.stories SET title = 'My interpretive dance about the two companies that own the world. Vanguard and BlackRock. In case you’re wondering why France is protesting!!! #capitalism #dance #money #business #wallstreet' WHERE slug = 'tiktok-7220880191634230574';
UPDATE public.stories SET title = '#worklifestruggle #work #worklife #futureofwork #ai #chatgptai #chatgpt #fakework #baudrillard #jeanbaudrillard #capitalismsucks #capitalismisadisease ' WHERE slug = 'tiktok-7220067938487766315';
UPDATE public.stories SET title = 'The secret sauce to Chat GPT is treating it like this #chatgpt #ai #entrepreneur #business #trading' WHERE slug = 'tiktok-7198217725947284778';
UPDATE public.stories SET title = 'Business school is walking down the street and studying a flourishing business #business #entrepreneur #sidehustle #businessideas #ecommerce ' WHERE slug = 'tiktok-7219167385213799685';
UPDATE public.stories SET title = 'Will AI Replace Humans: #AI #artificialintelligence  #dystopia #technology #gpt4 #robots  This dude claims that by By 2024 you will be able to replace around 50% of your software devselopers with GPT-4 agents that run on 10$ worth of tokens per hour. They won’t need sleep or breaks, and will cost 1/10th the cost of a human.  this is the claim of Mckay Wrigley, who for the past few weeks has been building AI applications with no code, and he even built jarvis which is an app on his mac where he spoke to it, and it  - Built and designed a frontend - Created a backend with working db - Correctly hooked those up - Uploaded code to GitHub - Deployed it online Things are heating up.  Smoke-away on twitter stated the following in a tweet: - GPT-5 is coming. - Midjourney v6 is coming. - Stable Diffusion 3 is coming. - Google still hasn''t caught OpenAI. - Humanoid robots are in production. - DeepMind and Google Brain joined forces. - AutoGPTs are coming. And for those who don’t know, AutoGPT is basically ChatGPT that runs autonomously, has a memory, and has a goal, and is programmed to stop once it reaches that goal, and it uses the GPT-4 API to prompt itself different things until the goal is reached.  And Sully asked AutoGPT to build a website and it did it in 3 minutes.  The AI doomers say that this will kill us all for sure. Eliezer Yadkowski said that it’s not that AI hates us, its that Humans are made of atoms and those Atoms could be used for something else.  The technooptimists say that Artificial General intelligence will lead us to nucular fusion which will allow us to turn all salt water into fresh water for almost no cost, and we will even be able to solve aging. And I’m not sure I know where I stand on this matter, I’m no scientist, but I do know it’s almost impossible to stop. Companies have a fiduciary responsibility to their shareholders, which means that within the law, they have an obligation to make decisions that maximize share price, which if you ask me, is a mentality that has lead us into really really really fucked up situations time and time again.  All I can do is spread awareness as things unfold. Follow for that.' WHERE slug = 'tiktok-7219692656186854702';
UPDATE public.stories SET title = 'Game-changer #chatgpt #googlesheets #hacks #sheetgpt #fyp  ' WHERE slug = 'tiktok-7205785788741651754';
UPDATE public.stories SET title = '#autogpt runs automatically #gpt4 #chatgpt #agi is here' WHERE slug = 'tiktok-7219888817916874026';
UPDATE public.stories SET title = 'Replying to @tsuku_yomii_ #greenscreen what is Christ consciousness? #jesus #christconsciousness #religion #lawofone #ascension #lowfrequency #highfrequency #lightbeings #guardianangel ' WHERE slug = 'tiktok-7218977083802864939';
UPDATE public.stories SET title = 'golden oldie ✨ my bootleg of Sweet Disposition by @The Temper Trap ' WHERE slug = 'tiktok-7208834010124913925';
UPDATE public.stories SET title = 'writing it out like this makes it so much easier to think about in my brain but if this overwhelms you, DM me and I’ll help you out 💗 #socialmediamanager #contentcreator #socialmediastrategy #contentstrategy #marketingstrategy #socialmediacontenttips ' WHERE slug = 'tiktok-7216436505571560746';
UPDATE public.stories SET title = '#stitch with @hankgreen1 big bang  #spacepoetry #cosmos #spokenword' WHERE slug = 'tiktok-7218360917774355754';
UPDATE public.stories SET title = 'Step by step tutorial on how to build your brand, Part 1. #brand #goals #personalbrand #businessgrowth #wmh #billharper #branding #marketing #inspiration #entrepreneur #HowTo ' WHERE slug = 'tiktok-7207782246474960171';
UPDATE public.stories SET title = 'don''t be shy. get super specific with chatgpt. the better the prompts the better the output EVERYONE KNOWS THAT! #moneymoves #ai #openai #chatgpt #chatgpt4 #artificalintelligence #genuis #prompts #chatgptprompts #becomeagenuis #freelance #freelancer #sidehustle #work #success #getaraise #makelifeeasier #digitalmarketing #no9to5 #nojob #antiworkaholic #10hr10kworkmonth #letsgo #wfh #wfhhacks ' WHERE slug = 'tiktok-7219030082466123050';
UPDATE public.stories SET title = 'What did you learn from this video???  Earrings by @aoqili1  #aneliasutton #legaltips #knowyourrights #justice #advocate #court #usa #legaleducation #childsupport #familycourt #rabbitshowtv ' WHERE slug = 'tiktok-7217935274528066859';
UPDATE public.stories SET title = 'Internal company processes with ChatGPT #chatgpt #chatgpthack #openai #chatgpt3 #chatgpt4 #chatgptprompt #chatgpttutorial #ai #chatgptforcreators #freeguide #chatgptforbusiness' WHERE slug = 'tiktok-7218281665016122651';
UPDATE public.stories SET title = '#stitch with @ispeak1906 @cre8tive_mindz Another important moment in black history #ispeak1906 #drhadiyahgreen #consciousleespeaks #cre8tive_mindz #be_original ' WHERE slug = 'tiktok-7196139647959928107';
UPDATE public.stories SET title = 'Secret Chatgpt prompt library that has been here the whole time! #openai #chatgpt #ai #artificialintelligence #brandnat #nataliechoprasert #promptengineering ' WHERE slug = 'tiktok-7217785797095869697';
UPDATE public.stories SET title = 'Dropping more tips off social media pull up and sign up for the notifications at the end of the video  Earrings by @aoqili1  #legaltips #legaleducation #knowyourrights #justice #advocate #court #law #usa ' WHERE slug = 'tiktok-7216842770969824558';
UPDATE public.stories SET title = 'The RESTRICT ACT known as the tiktok ban, bill S.686 is a terrifying bill that bans more than just tiktok. #tiktok #tiktokban #unitedstates #politics #bills686 ' WHERE slug = 'tiktok-7215293810912480558';
UPDATE public.stories SET title = 'This might be the most outrageous #facebookads hack I’ve heard yet…my goodness 😂 Will share some of my own from the early FB ads days…used to be the wild west 🤠 #socialmediamarketing #facebooktips #lukebelmar ' WHERE slug = 'tiktok-7210894112751373614';
UPDATE public.stories SET title = 'Replying to @soyalejandrolevel 5 big things happened in AI today. Heres what I paid attention to. #rachelwoods #chatgpt #gpt4 #aiwars #aiforwork #openai #adept #anthropic #claude ' WHERE slug = 'tiktok-7210622981930798378';
UPDATE public.stories SET title = 'This is Insane 🤯 #viral #fyp #iad #tech ' WHERE slug = 'tiktok-7185194479740013850';
UPDATE public.stories SET title = 'Ready to level up your ChatGPT prompting skills? 💥 Join me as I uncover a powerful technique that the co-founder of OpenAI uses to get the best results from prompts!  In this video, I demonstrate how to craft the ultimate prompt to generate any type of content, from expert YouTube titles to social media posts, email marketing content, and beyond.  Unlock the secrets of AI and marketing 🎯, and learn how to responsibly wield this newfound power. 🌟 #ChatGPT #AIContentGenius #PromptProSecrets #ContentMastery #ChatGPTMasterclass #AIInnovation #NextLevelContent #DigitalMarketing #ContentCreationHack #ArtificialIntelligence #AIPoweredContent #LanguageModelSecrets #BoostYourContent #GrowthHacking #chatgptprompts' WHERE slug = 'tiktok-7212011306797370629';
UPDATE public.stories SET title = 'Replying to @ridertheterrier Teachers don’t even understand the system they’re participating in. Which means that it’s working as intended. It’s the biggest lie in our history. #educationtiktok #collegesucks #careertiktok #jobhunt ' WHERE slug = 'tiktok-7209068200087031086';
UPDATE public.stories SET title = '#greenscreen what is the role of #ai #chatgpt #gpt4 in #primaryeducation ? #informationeconomy #whitecollarproblems #openai #founderproblems #sharktank #allinpodcast #pitchdecktips #pitchtok #vctok #investing ' WHERE slug = 'tiktok-7180420716003675435';
UPDATE public.stories SET title = '#fyp #narcissists #setboundaries #settingboundaries #boundaries ' WHERE slug = 'tiktok-7201498954880699694';
UPDATE public.stories SET title = 'Meta’s LLaMA model was leaked and now we can run it on our own computers. Its not exactly the same as #gpt3 because it hasnt been fine tuned or trained to be good at chatting or following instructions. But it is a huge step forward in open source performance. #rachelwoods #chatgpt #promptengineering #opensource #meta #llamamodel #aiwars #generativeai ' WHERE slug = 'tiktok-7212245057443777835';
UPDATE public.stories SET title = 'How to use AI tools to make faceless videos' WHERE slug = 'tiktok-7209819478455078186';
UPDATE public.stories SET title = 'THE BEST LIST #unclecharles #realestate #realestateinvesting ' WHERE slug = 'tiktok-7198660274210049323';
UPDATE public.stories SET title = 'We may be past the days that hiring a ton of web developers is necessary for a small start-up. Thoughts on this new AI program? #artificialintelligence #ai #entrepreneur #allinpodcast #machinelearning #githubcopilot #galileo ' WHERE slug = 'tiktok-7199834146909261099';
UPDATE public.stories SET title = 'learn my progression to become the ultimate piano master ;-) check out my bio for my upcoming piano release 🎹🖤 #pianotutorial #chordprogressions #pianochords #learnontiktok ' WHERE slug = 'tiktok-7197804476554792198';
UPDATE public.stories SET title = 'Beat the banks! #compoundinterest ' WHERE slug = 'tiktok-7207594896880946438';
UPDATE public.stories SET title = 'Someone created a chat GPT Google sheets extension, and I had to share how I thought it would help people searching for jobs. I had to type in a few commands to come up with a list of companies, their CEOs, a list of LinkedIn messages, and a list of coffee chat questions. The opportunities are endless with chat GPT and Google sheets.  ##googlesheets##googlesheetstips##techtok##pivotintoproduct##chatgpt##techlayoffs##careertok' WHERE slug = 'tiktok-7206449503409409326';
UPDATE public.stories SET title = 'This is the industry’s new way of testing songs before spending money 🔥‼️‼️   #musiccareercoach #musicmarketing #musicindustry ' WHERE slug = 'tiktok-7194918435632041222';
UPDATE public.stories SET title = '👆🏽Whatever the mind can conceive and believe it can achieve #consciousness #motivation #mindset #lifesecrets #stepstosuccess #wealthymindset' WHERE slug = 'tiktok-7199509866866625793';
UPDATE public.stories SET title = 'This Is How The Richest Man Made His Money 💰 👑 #alexhormozi #moneymaker #richestman ' WHERE slug = 'tiktok-7201132547496103174';
UPDATE public.stories SET title = 'A smart ChatGPT SEO trick to help your website rock on Google! #chatgpt #seo #seoai #ai #artificialintelligence #gpt #marketingtips ' WHERE slug = 'tiktok-7192684177181936901';
UPDATE public.stories SET title = 'ChatGPT Makes Me Rich: My AI Trading Bot Story #cryptotrading #cryptocurrencytrading #altcointrading #cryptocurrency #btctrading #cryptomarket' WHERE slug = 'tiktok-7174957543985351942';
UPDATE public.stories SET title = 'Chat GPT prompts cheatsheet will make you look like a genius at work or school #freetime #studytipsguru #chatgpt #time #students #chatgpt3 #chatgpthack #aitools #contentcreators #businesscreators ' WHERE slug = 'tiktok-7192624667218169093';
UPDATE public.stories SET title = 'Good job Netflix, you geniuses. #netflix #pearlmania500 #philly #rant #itsgettingworse ' WHERE slug = 'tiktok-7195350372607905070';
UPDATE public.stories SET title = 'Don''t Explain. Explaining things especially to questions that don''t merit explanation undermine your credibility. Say, "It''s policy." #salestraining' WHERE slug = 'tiktok-7189791700435455275';
UPDATE public.stories SET title = 'Grab my fr33 eguide on how to market online.  If you want to sell kids books, journals or any other products- you need to learn digital marketing #chatgpt #makemoneyfromhome #howtobuildabusiness #retireyour925 #over50 #aitools ' WHERE slug = 'tiktok-7190746190768590123';
UPDATE public.stories SET title = 'Side Hustles I wish I knew sooner part 1!! Create continuous passive income!!Follow me for the best side hustles and ways to make income!! #sidehustle #workfromhome #sidehustles #makemoneyonline #FYP #Viral ' WHERE slug = 'tiktok-7181591920651537710';
UPDATE public.stories SET title = 'All economies, in fact all transactions, require asymmetric information and skill sets, otherwise they wouldn’t have value but if all asymmetric information is eliminated with anyone who has an internet connection, doesn’t that mean that all transactions based on knowledge work and by extension all markets for knowledge work implode? #Lawyers, #accountants, #marketers, #professors #designers #developers #journalists and dozens of other professions will be forced to integrate the very tools that will eliminate them. Also I misspoke, #chatgpt didn’t rewrite code it just wrote a different solution. #yc #openai #pitchdecktips #ycombinator #vctok #pitchtok #founderproblems #informationeconomy #nocode #allinpodcast #sharktank ' WHERE slug = 'tiktok-7174938701787680043';
UPDATE public.stories SET title = 'AOC exposes the problem with politics #leftist #politics #polititok #leftisttiktok #genz #liberal #congress ' WHERE slug = 'tiktok-7201268046260931883';
UPDATE public.stories SET title = '#iam #divine #powerwithin #godwithin #spiritual #wakeup #stayawake #knowledge #love #6millionfam #connected  ' WHERE slug = 'tiktok-7192085288804568362';
UPDATE public.stories SET title = '#trading #tradingcards #funny #humor #comedy #satire' WHERE slug = 'tiktok-7178697722814369070';
UPDATE public.stories SET title = 'Did you catch the 6th skill? 😁 looking at these, we change the game rather than play along, to win. #psychology #tricks #skills #wisdom #philosophy #selflove #selfcare #selfimprovement #happiness #socialskills ' WHERE slug = 'tiktok-7197922584871308590';
UPDATE public.stories SET title = 'Your anxiety is a communication from you to you about a part of yourself that needs healing. #ariansamouie #spirituality #love #spiritual #meditation #spiritualawakening #peace #healing #awakening #mindfulness #yoga #consciousness #life #wisdom #enlightenment ' WHERE slug = 'tiktok-7200324477014560005';
UPDATE public.stories SET title = 'This is how reality works. Now this story isn''t exactly what happens outside of the game. I created this story as a quick way of understanding what your reality is. your spiritual being already understood all if this and so much more was decided before you came into this game. #ariansamouie #spirituality #love #spiritual #meditation #spiritualawakening #peace #healing #awakening #mindfulness #yoga #consciousness #life #wisdom #enlightenment ' WHERE slug = 'tiktok-7194227035194051845';
UPDATE public.stories SET title = 'Soul vs. spirit #spirituality #selfhealing #selflove ' WHERE slug = 'tiktok-7196786014923296042';
UPDATE public.stories SET title = 'How best to prepare your kids for the future aka skills of the future.   #artificialintelligence #author #disruption #disruptivetechnology #emergingtech #futurism  #inspiration  #keynotespeaker #leadership #motivation #publicspeaker #publicspeaking #speaker #tedtalks #thindustrialrevolution' WHERE slug = 'tiktok-7176339893528939778';
UPDATE public.stories SET title = 'If you don’t know what prompt to use for ChatGPT, use this one… #artificialintelligence #openai #chatgpt #generativeai #chatgpttips  ' WHERE slug = 'tiktok-7196320340316998958';
UPDATE public.stories SET title = '#cathiewood #arc #crypto #cryptok #cryptoinvesting #investing #tiktokinvestor #plutosproject #fyp #cryptogreece #greektiktok #financialfreedom #hustle' WHERE slug = 'tiktok-7187372797507669254';
UPDATE public.stories SET title = 'Mediaopoly. Aired only once in 1998 on the live SNL show for which it was written and effectively banned and never aired again. Wonder why? #monopoly #illusionofchoice #disney ' WHERE slug = 'tiktok-7169757338231131438';
UPDATE public.stories SET title = 'Content Creator AI Tools Top 9 #midjourney #ai #chatgpt #synthesia #contentcreator #tiktoker #viral #fyp #foryou' WHERE slug = 'tiktok-7185618200644554027';
UPDATE public.stories SET title = 'Dr. Barkley on ADHD tips for parents. #TheIEPStrategist #ADHD #504 #specialneedsmom #russellbarkley #adhdkids #IEP #teachersoftiktok #iepmeetings #ParentsOfTikTok #specialneeds ' WHERE slug = 'tiktok-7178148881149250862';
UPDATE public.stories SET title = 'Athletique is such a great brand - I wonder what it would be like to actually start it…. #chatgpt #midjourney #openai #ai #adworld ' WHERE slug = 'tiktok-7188273191494749441';
UPDATE public.stories SET title = 'AI creative tools. Time to be creatice #ChatGPT #midjourney #aiart #videoeditor #premierepro #animation #blender #blender3d ' WHERE slug = 'tiktok-7188974400606194987';
UPDATE public.stories SET title = '"JVKE - golden hour" Piano easy🎹 You only need 1min to play #tutorial #music #fyp #foryou #피아노 #골든아워 #튜토리얼 #추천떠라' WHERE slug = 'tiktok-7160933437170273538';